apiVersion: vi
kind: Deployment
metedata:
  name: ID1-deploy
spec:
  replicas: 3
  minReadyseconds: 20
  template:
    metadata:
      labels:
        app: ID1
    spec:
      containers:
        name: ID1
        image: kondaiahgovindu/ID1
        ports:
          containerport:6000
